-- Phase 5: utilization_vehicle 테이블 생성 (가동률 정보)
-- 기존 데이터 삭제 후 테이블 재성성

-- 1) 기존 테이블 삭제
DROP TABLE IF EXISTS public.utilization_vehicle CASCADE;

-- 2) utilization_vehicle 테이블 생성
CREATE TABLE public.utilization_vehicle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cmny_id INTEGER NOT NULL REFERENCES public.companies(cmny_id) ON DELETE CASCADE,
  year_month CHAR(6) NOT NULL, -- 'YYYYMM' 형식
  vehicle_no TEXT NOT NULL,
  vehicle_model TEXT,
  driving_minutes INTEGER DEFAULT 0,
  utilization_pct NUMERIC(5,2) DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3) 인덱스 및 제약 조건 생성
CREATE INDEX utilization_vehicle_cmny_year_month_idx ON public.utilization_vehicle(cmny_id, year_month);
CREATE INDEX utilization_vehicle_vehicle_no_idx ON public.utilization_vehicle(vehicle_no);
CREATE INDEX utilization_vehicle_model_idx ON public.utilization_vehicle(vehicle_model);

-- 중복 방지 및 Upsert를 위한 유니크 제약 조건
ALTER TABLE public.utilization_vehicle 
ADD CONSTRAINT utilization_vehicle_unique_key UNIQUE (cmny_id, year_month, vehicle_no);

-- 4) RLS 활성화
ALTER TABLE public.utilization_vehicle ENABLE ROW LEVEL SECURITY;

-- 5) RLS 정책
-- 승인된 사용자는 조회가 가능하도록 설정 (필요에 따라 더 엄격하게 제한 가능)
CREATE POLICY "Approved users can view all utilization records"
  ON public.utilization_vehicle
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE user_id = auth.uid()
      AND is_approved = TRUE
    )
  );

-- Admin만 삽입/수정/삭제 가능
CREATE POLICY "Admins can insert utilization records"
  ON public.utilization_vehicle
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE user_id = auth.uid()
      AND role = 'admin'
    )
  );

CREATE POLICY "Admins can update utilization records"
  ON public.utilization_vehicle
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE user_id = auth.uid()
      AND role = 'admin'
    )
  );

CREATE POLICY "Admins can delete utilization records"
  ON public.utilization_vehicle
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE user_id = auth.uid()
      AND role = 'admin'
    )
  );

-- 6) updated_at 자동 업데이트 트리거
CREATE TRIGGER set_utilization_vehicle_updated_at
  BEFORE UPDATE ON public.utilization_vehicle
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();
